version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/code
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./code:/var/code
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 33060:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret